# Remote execution config for GCP gigafleet
# Copy to .buckconfig.local to enable RE:
#   cat .sensenet/remote-gcp.ini >> .buckconfig.local

[build]
execution_platforms = toolchains//:lre

[buck2_re_client]
engine_address = grpc://34.28.196.149:50051
cas_address = grpc://34.28.196.149:50051
action_cache_address = grpc://34.28.196.149:50051
tls = false
instance_name = 

[buck2_re_client.platform_properties]
OSFamily = linux
container-image = sensenet-worker
toolchains = cxx,rust,haskell
ISA = x86-64
