-- AUTO-GENERATED by nix develop
-- DO NOT EDIT - regenerated on each shell entry
let TC = ../dhall/Toolchains.dhall

let cxxToolchain : TC.Cxx =
  { image = None Text
  , cc = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/clang"
  , cxx = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/clang++"
  , ar = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/llvm-ar"
  , ld = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/ld.lld"
  , paths = TC.paths 
      [ "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/include/c++/15.2.0"
      , "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/include/c++/15.2.0/x86_64-unknown-linux-gnu"
      , "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/lib/clang/22/include"
      , "/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include"
      ]
      [ "/nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib"
      , "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/lib/gcc/x86_64-unknown-linux-gnu/15.2.0"
      , "/nix/store/xc0ga87wdclrx54qjaryahkkmkmqi9qz-gcc-15.2.0-lib/lib"
      ]
  , sysroot = ""
  , target = "x86_64-unknown-linux-gnu"
  }

let rustToolchain : TC.Rust =
  { image = None Text
  , rustc = TC.tool "/nix/store/lvdr3nws8gs2qcgm3rnwvjprcx55kx7l-rustc-wrapper-1.91.1/bin/rustc"
  , cargo = TC.tool "/nix/store/9db7xb1axdgqp4lakdxbp27yh7kfvm0b-cargo-1.91.1/bin/cargo"
  , edition = "2021"
  , target = "x86_64-unknown-linux-gnu"
  }

let haskellToolchain : TC.Haskell =
  { image = None Text
  , ghc = TC.tool "/nix/store/dq5xs27h4q02468kbngiszpcgs1q0vay-ghc-9.12.2-with-packages/bin/ghc"
  , ghc_pkg = TC.tool "/nix/store/dq5xs27h4q02468kbngiszpcgs1q0vay-ghc-9.12.2-with-packages/bin/ghc-pkg"
  , paths = TC.emptyPaths
  }

let leanToolchain : TC.Lean =
  { image = None Text
  , lean = TC.tool "/nix/store/hgrr6brn6gxwrzz2z8yca82r0mhhm08r-lean4-4.26.0/bin/lean"
  , leanc = TC.tool "/nix/store/hgrr6brn6gxwrzz2z8yca82r0mhhm08r-lean4-4.26.0/bin/leanc"
  , paths = TC.emptyPaths
  }

let purescriptToolchain : TC.PureScript =
  { image = None Text
  , purs = TC.tool "/nix/store/501niw8ss2ndcs3ij3gz7wiqfsc72w7r-purs-0.15.15/bin/purs"
  , spago = TC.tool "/nix/store/r8h89s810fgpcf331jijhxs0vjh3h3h9-spago-1.0.3/bin/spago"
  , node = TC.tool "/nix/store/cikdc61gfwvdma6y0p9b5d5d448aqcv6-nodejs-24.12.0/bin/node"
  , esbuild = TC.tool "/nix/store/2mq1i9wsyfl25ni0ai9s97268mri01vd-esbuild-0.25.5/bin/esbuild"
  }

let nvToolchain : TC.Nv =
  { image = None Text
  , clang = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/clang++"
  , ptxas = TC.tool "/nix/store/71bcxdmr93ylizg47gnfvk8wdaqds7hd-nvidia-sdk-13.1/bin/ptxas"
  , fatbinary = TC.tool "/nix/store/71bcxdmr93ylizg47gnfvk8wdaqds7hd-nvidia-sdk-13.1/bin/fatbinary"
  , sdk_path = "/nix/store/71bcxdmr93ylizg47gnfvk8wdaqds7hd-nvidia-sdk-13.1"
  , sdk = TC.paths 
      [ "/nix/store/71bcxdmr93ylizg47gnfvk8wdaqds7hd-nvidia-sdk-13.1/include" ]
      [ "/nix/store/71bcxdmr93ylizg47gnfvk8wdaqds7hd-nvidia-sdk-13.1/lib" ]
  , archs = ["sm_90", "sm_100", "sm_120"]
  , cxx = cxxToolchain
  }


in  { cxx = cxxToolchain
    , nv = Some nvToolchain
    , rust = rustToolchain
    , haskell = haskellToolchain
    , lean = leanToolchain
    , purescript = purescriptToolchain
    } : TC.Toolchains
