-- Generated by nix develop
let TC = ../dhall/Toolchains.dhall

let cxxToolchain : TC.Cxx =
  { image = None Text
  , cc = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/clang"
  , cxx = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/clang++"
  , ar = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/llvm-ar"
  , ld = TC.tool "/nix/store/rwv3n4h5wrin94j6mzdhjlbs06br9a8x-llvm-git-22.0.0-straylight/bin/ld.lld"
  , paths = TC.emptyPaths
  , sysroot = ""
  , target = "aarch64-unknown-linux-gnu"
  }

let rustToolchain : TC.Rust =
  { image = None Text
  , rustc = TC.tool ""
  , cargo = TC.tool ""
  , edition = "2021"
  , target = "aarch64-unknown-linux-gnu"
  }

let haskellToolchain : TC.Haskell =
  { image = None Text
  , ghc = TC.tool "/nix/store/dq5xs27h4q02468kbngiszpcgs1q0vay-ghc-9.12.2-with-packages/bin/ghc"
  , ghc_pkg = TC.tool "/nix/store/dq5xs27h4q02468kbngiszpcgs1q0vay-ghc-9.12.2-with-packages/bin/ghc-pkg"
  , paths = TC.emptyPaths
  }

let leanToolchain : TC.Lean =
  { image = None Text
  , lean = TC.tool ""
  , leanc = TC.tool ""
  , paths = TC.emptyPaths
  }

let purescriptToolchain : TC.PureScript =
  { image = None Text
  , purs = TC.tool "/nix/store/501niw8ss2ndcs3ij3gz7wiqfsc72w7r-purs-0.15.15/bin/purs"
  , spago = TC.tool "/nix/store/r8h89s810fgpcf331jijhxs0vjh3h3h9-spago-1.0.3/bin/spago"
  , node = TC.tool "/home/b7r6/.nix-profile/bin/node"
  , esbuild = TC.tool "/nix/store/2mq1i9wsyfl25ni0ai9s97268mri01vd-esbuild-0.25.5/bin/esbuild"
  }

in  { cxx = cxxToolchain
    , nv = None TC.Nv
    , rust = rustToolchain
    , haskell = haskellToolchain
    , lean = leanToolchain
    , purescript = purescriptToolchain
    } : TC.Toolchains
