--| Toolchain definitions for sensenet
--|
--| All tools come from Nix devshell with absolute Nix store paths.
--| Paths are read from .buckconfig.local, generated by shellHook.
--|
--| Build: ../dhall-to-buck BUILD.dhall > BUCK

let A = ../dhall/prelude/package.dhall
let S = ../dhall/prelude/to-starlark.dhall

-- ══════════════════════════════════════════════════════════════════════════════
-- C++ (LLVM)
-- ══════════════════════════════════════════════════════════════════════════════

let cxx =
      (A.cxxToolchain "cxx")
        with c_extra_flags = [ "-std=c23", "-Wall", "-Wextra" ]
        with cxx_extra_flags = [ "-std=c++23", "-Wall", "-Wextra", "-fno-exceptions" ]
        with link_style = "static"

-- ══════════════════════════════════════════════════════════════════════════════
-- Haskell (GHC from Nix)
-- ══════════════════════════════════════════════════════════════════════════════

let haskell =
      (A.haskellToolchain "haskell")
        with compiler_flags = [ "-Wall", "-Werror", "-XGHC2024", "-fwrite-ide-info", "-hiedir=buck-out/hie" ]

-- ══════════════════════════════════════════════════════════════════════════════
-- Execution Platforms
-- ══════════════════════════════════════════════════════════════════════════════

let lre =
      (A.executionPlatform "lre")
        with local_enabled = True
        with remote_enabled = True

let local =
      (A.executionPlatform "local")
        with local_enabled = True
        with remote_enabled = False

-- ══════════════════════════════════════════════════════════════════════════════
-- Required Bootstrap Toolchains
-- ══════════════════════════════════════════════════════════════════════════════

let pythonBootstrap = A.pythonBootstrap "python_bootstrap"
let genrule = A.genruleToolchain "genrule"

in  { rules =
        [ S.cxxToolchain cxx
        , S.haskellToolchain haskell
        , S.executionPlatform lre
        , S.executionPlatform local
        , S.pythonBootstrap pythonBootstrap
        , S.genruleToolchain genrule
        ]
    , header = ''
        # Generated from BUILD.dhall
        # Toolchain definitions for sensenet
        #
        # Note: nv_toolchain, rust_toolchain, lean_toolchain, purescript_toolchain
        # are not yet ported to Dhall. Add them here when needed.

        load(":cxx.bzl", "llvm_toolchain")
        load(":haskell.bzl", "haskell_toolchain")
        load(":execution.bzl", "lre_execution_platform", "host_configuration")
        load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
        load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
        ''
    }
