{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExtendedDefaultRules #-}
{-# OPTIONS_GHC -fno-warn-type-defaults #-}

{- |
Module      : SenseNet.Generate
Description : Generate BUCK files and project structure

Parses BUILD.dhall files natively in Haskell, constructs the typed IR,
and emits BUCK files. No shelling out to dhall CLI.

The generated structure is ephemeral — it exists only to extract
DICE + TUI behavior from Buck2.
-}
module SenseNet.Generate
  ( generate
  , generateBuck
  , copyPrelude
  , copyToolchains
  , writeBuckconfig
  ) where

import Control.Exception (try, SomeException)
import Data.Text (Text)
import qualified Data.Text as T
import Shelly hiding ((</>))
import System.Directory (doesDirectoryExist, doesFileExist)
import System.FilePath ((</>), takeDirectory)

import SenseNet.Config
import SenseNet.Discover
import SenseNet.Emit (emitBuck)
import qualified SenseNet.Dhall as Dhall

default (Text)

-- | Generate the complete project structure in tmpdir
generate :: Config -> [DhallFile] -> Sh ()
generate cfg files = do
  -- Create tmpdir structure
  mkdir_p (fromText $ T.pack $ tmpDir cfg)
  
  -- Copy prelude and toolchains
  copyPrelude cfg
  copyToolchains cfg
  
  -- Generate BUCK files
  mapM_ (generateBuck cfg) files
  
  -- Write .buckconfig
  writeBuckconfig cfg

-- | Generate a single BUCK file from a BUILD.dhall file
generateBuck :: Config -> DhallFile -> Sh ()
generateBuck cfg file = do
  -- Only process BUILD.dhall files (not .new suffix for now, handle both)
  let path = dhallPath file
      isBuildDhall = "BUILD.dhall" `T.isSuffixOf` T.pack path
  
  when isBuildDhall $ do
    -- Output goes to tmpdir mirroring the source structure
    let srcDir = takeDirectory (dhallRelPath file)
        outDir = tmpDir cfg </> srcDir
        outPath = outDir </> "BUCK"
    
    mkdir_p (fromText $ T.pack outDir)
    
    -- Try new format first (native Haskell parsing)
    result <- liftIO $ try $ Dhall.parsePackageFile (projectRoot cfg) path
    
    case result of
      Right pkg -> do
        -- New format: emit from IR
        let content = "# Generated by sensenet from " <> T.pack path <> "\n\n" <> emitBuck pkg
        writefile (fromText $ T.pack outPath) content
        echo $ "gen: " <> T.pack (dhallRelPath file) <> " -> " <> T.pack outPath
      
      Left (_ :: SomeException) -> do
        -- Fall back to legacy format (dhall CLI)
        content <- evalLegacyFormat path
        writefile (fromText $ T.pack outPath) content
        echo $ "gen (legacy): " <> T.pack (dhallRelPath file) <> " -> " <> T.pack outPath

-- | Evaluate legacy format: { rules : List Text, header : Text }
-- This is the old format that uses to-starlark.dhall
evalLegacyFormat :: FilePath -> Sh Text
evalLegacyFormat fp = do
  let dhallPathText = toDhallPath fp
  
  -- Check if it's the old format with rules/header
  typeOut <- run "dhall" ["type", "--file", T.pack fp]
  
  if "rules" `T.isInfixOf` typeOut && "header" `T.isInfixOf` typeOut
    then do
      -- Old format: { rules : List Text, header : Text }
      header <- run "bash" ["-c", "dhall text <<< '(" <> dhallPathText <> ").header'"]
      let rulesCmd = "dhall text <<< 'let P = ./dhall/prelude/Prelude.dhall in P.Text.concatSep \"\\n\" (" <> dhallPathText <> ").rules'"
      rules <- run "bash" ["-c", rulesCmd]
      pure $ T.unlines
        [ "# Generated from " <> T.pack fp <> " (legacy format)"
        , header
        , rules
        ]
    else do
      -- Very old format: direct dhall-to-buck script
      run "./dhall-to-buck" [T.pack fp]

-- | Convert filepath to Dhall import path
toDhallPath :: FilePath -> Text
toDhallPath fp
  | "/" `T.isPrefixOf` T.pack fp = T.pack fp  -- absolute path
  | otherwise = "./" <> T.pack fp              -- relative path

-- | Copy prelude to tmpdir
copyPrelude :: Config -> Sh ()
copyPrelude cfg = do
  let src = fromText $ T.pack $ preludePath cfg
      dst = fromText $ T.pack $ generatedPrelude cfg
  cp_r src dst
  echo $ "copy: prelude -> " <> T.pack (generatedPrelude cfg)

-- | Copy toolchains to tmpdir
-- Prefer local project toolchains over Nix store path
copyToolchains :: Config -> Sh ()
copyToolchains cfg = do
  let localToolchains = projectRoot cfg </> "toolchains"
      nixToolchains = toolchainsPath cfg
      dst = fromText $ T.pack $ generatedToolchains cfg
  
  -- Check if local toolchains exist (working directory)
  localExists <- liftIO $ doesDirectoryExist localToolchains
  localHasBzl <- if localExists 
                   then liftIO $ doesFileExist (localToolchains </> "cxx.bzl")
                   else pure False
  
  let src = if localHasBzl then localToolchains else nixToolchains
  cp_r (fromText $ T.pack src) dst
  echo $ "copy: toolchains (" <> (if localHasBzl then "local" else "nix") <> ") -> " <> T.pack (generatedToolchains cfg)

-- | Write .buckconfig pointing to bind-mounted paths
-- 
-- Cell paths are relative to the project root (where .buckconfig lives).
-- We bind-mount prelude/ and toolchains/ directly at project root.
writeBuckconfig :: Config -> Sh ()
writeBuckconfig cfg = do
  let content = T.unlines
        [ "# Generated by sensenet"
        , ""
        , "[cells]"
        , "root = ."
        , "prelude = prelude"
        , "toolchains = toolchains"
        , "none = none"
        , ""
        , "[cell_aliases]"
        , "config = prelude"
        , "ovr_config = prelude"
        , "fbcode = none"
        , "fbsource = none"
        , "fbcode_macros = none"
        , "buck = none"
        , ""
        , "[parser]"
        , "target_platform_detector_spec = target:root//...->prelude//platforms:default"
        , ""
        , "[buck2]"
        , "materializations = deferred"
        , "digest_algorithms = BLAKE3"
        , ""
        , "[build]"
        , "execution_platforms = toolchains//:local"
        ]
  writefile (fromText $ T.pack $ generatedBuckconfig cfg) content
  echo "gen: .buckconfig"
