{- test/sensenet/proof-obligations.dhall

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                                  // test // proof-obligations //
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   FAILING TEST: Verify proof obligations are correctly typed and satisfiable

   This test file exercises the DischargeProof.dhall types to ensure:
     1. Pure builds have empty coeffect requirements
     2. Network builds have NetworkAccess evidence
     3. Proofs compose correctly under the tensor product

   Currently fails because:
     1. No Lean4 formalization exists to verify the proofs
     2. Cross-language verification (Dhall → Lean) not implemented
     3. Proof witnesses not generated by build system yet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-}

let DischargeProof = ../../dhall/DischargeProof.dhall
let Resource = ../../dhall/Resource.dhall

--------------------------------------------------------------------------------
-- Test 1: Pure build proof
--
-- A pure build should have:
--   - Empty coeffects (Resource.pure)
--   - No network access evidence
--   - No filesystem access evidence
--------------------------------------------------------------------------------

let test-pure-proof : DischargeProof.DischargeProof =
    DischargeProof.pureProof
      { buildId = "test-pure-001"
      , derivationHash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
      , outputHashes = [ { name = "out", hash = "sha256:1111111111111111111111111111111111111111111111111111111111111111" } ]
      , startTime = "2025-02-12T00:00:00Z"
      , endTime = "2025-02-12T00:00:01Z"
      }

-- Assertion: pure proof should be pure
let _ = assert : DischargeProof.isPure test-pure-proof === True

-- Assertion: pure proof should have no network evidence
let _ = assert : DischargeProof.hasNetworkEvidence test-pure-proof === False

--------------------------------------------------------------------------------
-- Test 2: Network build proof
--
-- A build that fetches from network should have:
--   - Network in coeffects
--   - NetworkAccess evidence with content hash
--------------------------------------------------------------------------------

let test-network-proof : DischargeProof.DischargeProof =
    { coeffects = Resource.network
    , networkAccess =
        [ { url = "https://github.com/example/repo/archive/main.tar.gz"
          , method = "GET"
          , contentHash = "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
          , timestamp = "2025-02-12T00:00:00Z"
          }
        ]
    , filesystemAccess = [] : List DischargeProof.FilesystemAccess
    , authUsage = [] : List DischargeProof.AuthUsage
    , buildId = "test-network-001"
    , derivationHash = "sha256:2222222222222222222222222222222222222222222222222222222222222222"
    , outputHashes = [ { name = "out", hash = "sha256:3333333333333333333333333333333333333333333333333333333333333333" } ]
    , startTime = "2025-02-12T00:00:00Z"
    , endTime = "2025-02-12T00:00:05Z"
    , signature = None { publicKey : Text, sig : Text }
    }

-- Assertion: network proof should NOT be pure
let _ = assert : DischargeProof.isPure test-network-proof === False

-- Assertion: network proof should have network evidence
let _ = assert : DischargeProof.hasNetworkEvidence test-network-proof === True

--------------------------------------------------------------------------------
-- Test 3: Combined coeffects
--
-- When builds compose, coeffects should combine via tensor product
--------------------------------------------------------------------------------

let combined-coeffects : Resource.Resources =
    Resource.combine
      Resource.network
      (Resource.auth "github")

-- FAILING: This needs Lean4 verification that:
--   network ⊗ auth("github") 
--   is satisfied by evidence with both NetworkAccess AND AuthUsage

let test-combined-proof : DischargeProof.DischargeProof =
    { coeffects = combined-coeffects
    , networkAccess =
        [ { url = "https://api.github.com/repos/example/repo"
          , method = "GET"
          , contentHash = "sha256:4444444444444444444444444444444444444444444444444444444444444444"
          , timestamp = "2025-02-12T00:00:00Z"
          }
        ]
    , filesystemAccess = [] : List DischargeProof.FilesystemAccess
    , authUsage =
        [ { provider = "github"
          , scope = Some "repo:read"
          , timestamp = "2025-02-12T00:00:00Z"
          }
        ]
    , buildId = "test-combined-001"
    , derivationHash = "sha256:5555555555555555555555555555555555555555555555555555555555555555"
    , outputHashes = [ { name = "out", hash = "sha256:6666666666666666666666666666666666666666666666666666666666666666" } ]
    , startTime = "2025-02-12T00:00:00Z"
    , endTime = "2025-02-12T00:00:10Z"
    , signature = None { publicKey : Text, sig : Text }
    }

--------------------------------------------------------------------------------
-- Test 4: Insufficient evidence (SHOULD FAIL at verification time)
--
-- A proof that claims network coeffect but provides no evidence
-- This is WELL-TYPED in Dhall but should be REJECTED by Lean4 verifier
--------------------------------------------------------------------------------

let test-insufficient-proof : DischargeProof.DischargeProof =
    { coeffects = Resource.network  -- claims to need network
    , networkAccess = [] : List DischargeProof.NetworkAccess  -- BUT no evidence!
    , filesystemAccess = [] : List DischargeProof.FilesystemAccess
    , authUsage = [] : List DischargeProof.AuthUsage
    , buildId = "test-insufficient-001"
    , derivationHash = "sha256:7777777777777777777777777777777777777777777777777777777777777777"
    , outputHashes = [ { name = "out", hash = "sha256:8888888888888888888888888888888888888888888888888888888888888888" } ]
    , startTime = "2025-02-12T00:00:00Z"
    , endTime = "2025-02-12T00:00:01Z"
    , signature = None { publicKey : Text, sig : Text }
    }

-- This type-checks in Dhall but should fail Lean4 verification:
-- FAILING: No verifier to reject this yet

--------------------------------------------------------------------------------
-- Export all tests
--------------------------------------------------------------------------------

in  { test-pure-proof
    , test-network-proof
    , test-combined-proof
    , test-insufficient-proof
    }
