-- buckconfig-local.dhall
-- Generate buckconfig.local header

let sections = env:SECTIONS as Text

in ''
# AUTO-GENERATED by nix develop
# DO NOT EDIT - regenerated on each shell entry
${sections}
''
