--| slide - Console cowboy for the sprawl
--|
--| Ingress adapter that jacks into OpenAI-compatible inference endpoints,
--| parses their SSE/JSON garbage, and emits clean SIGIL binary frames over ZMQ.
--|
--| Build: ./dhall-to-buck src/slide/BUILD.dhall > src/slide/BUCK

let A = ../../dhall/prelude/package.dhall
let S = ../../dhall/prelude/to-starlark.dhall

-- Library sources (all modules under src/Slide/)
let librarySrcs =
      [ "src/Slide/Chunk.hs"
      , "src/Slide/Configuration.hs"
      , "src/Slide/HotTable.hs"
      , "src/Slide/Model.hs"
      , "src/Slide/Parse.hs"
      , "src/Slide/Provider.hs"
      , "src/Slide/Provider/HTTP2.hs"
      , "src/Slide/Provider/OpenAI.hs"
      , "src/Slide/Provider/OpenRouter.hs"
      , "src/Slide/Provider/Vertex/Anthropic.hs"
      , "src/Slide/Tokenizer.hs"
      , "src/Slide/Tokenizer/FFI.hs"
      , "src/Slide/Wire/Decode.hs"
      , "src/Slide/Wire/Encode.hs"
      , "src/Slide/Wire/Frame.hs"
      , "src/Slide/Wire/Types.hs"
      , "src/Slide/Wire/Varint.hs"
      ]

-- Executable sources
let appSrcs = [ "app/Main.hs" ]

-- Test sources
let testSrcs =
      [ "test/Spec.hs"
      , "test/ChunkSpec.hs"
      , "test/ConfigurationSpec.hs"
      , "test/DecodeSpec.hs"
      , "test/EncodeSpec.hs"
      , "test/FrameSpec.hs"
      , "test/HotTableSpec.hs"
      , "test/ModelSpec.hs"
      , "test/ParseSpec.hs"
      , "test/RoundtripSpec.hs"
      , "test/TokenizerFFISpec.hs"
      , "test/ToolCallSpec.hs"
      , "test/TypesSpec.hs"
      , "test/VarintSpec.hs"
      ]

-- C++ FFI sources for tokenizers binding
let cxxSrcs = [ "cbits/tokenizers_c.cpp" ]

-- All Haskell packages needed
let packages =
      [ "base"
      , "aeson"
      , "async"
      , "blake3"
      , "bytestring"
      , "case-insensitive"
      , "containers"
      , "crypton"
      , "data-default-class"
      , "dhall"
      , "http2"
      , "http-semantics"
      , "http-types"
      , "katip"
      , "megaparsec"
      , "memory"
      , "network"
      , "optparse-applicative"
      , "prometheus-client"
      , "prometheus-metrics-ghc"
      , "random"
      , "text"
      , "time-manager"
      , "tls"
      , "vector"
      , "wai"
      , "warp"
      , "zeromq4-haskell"
      ]

-- Language extensions
let extensions =
      [ "BangPatterns"
      , "CApiFFI"
      , "DerivingStrategies"
      , "ForeignFunctionInterface"
      , "LambdaCase"
      , "NumericUnderscores"
      , "OverloadedStrings"
      , "PatternSynonyms"
      , "StrictData"
      ]

-- GHC options
let ghcOptions =
      [ "-O2"
      , "-threaded"
      , "-rtsopts"
      , "-with-rtsopts=-N -A64m -I0"
      , "-isrc"
      ]

-- External libraries (from Nix via .buckconfig.local)
-- These paths are injected by the shell hook from extraBuckconfigSections
let extraLibs =
      [ "tokenizers_cpp"
      , "tokenizers_c"
      , "sentencepiece"
      ]

-- slide executable with FFI
-- NOTE: extra_lib_dirs and include_dirs are read from .buckconfig.local [slide] section
-- which is generated by nix develop from flake.nix extraBuckconfigSections
let slide =
      (A.haskellFFIBinary "slide" (librarySrcs # appSrcs) cxxSrcs)
        with packages = packages
        with language_extensions = extensions
        with ghc_options = ghcOptions
        with extra_libs = extraLibs
        with include_dirs = [ "src/slide/cbits" ]

in  { rules = [ S.haskellFFIBinary slide ]
    , header = ''
        # Generated from BUILD.dhall
        # 
        # Library paths for tokenizers-cpp come from .buckconfig.local [slide] section
        # which is auto-generated by `nix develop .#buck2-slide`
        # The haskell_ffi_binary rule reads these paths via read_root_config()
        
        load("@toolchains//:haskell.bzl", "haskell_ffi_binary")
        ''
    }
