# Generated by: nix run nixpkgs#cabal2nix -- .
# To regenerate: nix run nixpkgs#cabal2nix -- . > nix/packages/sensenet.nix
# Note: dice-ffi added manually for FFI bindings
{
  mkDerivation,
  base,
  bytestring,
  containers,
  dhall,
  directory,
  filepath,
  lib,
  process,
  shelly,
  temporary,
  text,
  unix,
  dice-ffi,
}:
mkDerivation {
  pname = "sensenet";
  version = "0.1.0";
  src = lib.cleanSource ../../.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    bytestring
    containers
    dhall
    directory
    filepath
    process
    shelly
    temporary
    text
    unix
  ];
  executableSystemDepends = [ dice-ffi ];
  description = "SENSE // NET — Typed builds with Dhall + DICE";
  license = lib.licenses.mit;
  mainProgram = "sensenet";
  # Skip patch phase (no patches needed)
  patchPhase = ":";
}
