# nix/modules/flake/buck2/toolchain.nix
#
# Generate .buckconfig.local content for a Buck2 project.
#
{ lib, pkgs }:
let
  # Import centralized render-dhall function
  render-dhall = import ../../../lib/render-dhall.nix { inherit pkgs lib; };

  # Scripts directory for Dhall templates
  scripts-dir = ./toolchains;
in
{
  # Generate buckconfig.local INI content from toolchain config
  mkBuckconfigLocal =
    {
      cxx ? null,
      haskell ? null,
      rust ? null,
      lean ? null,
      python ? null,
      nv ? null,
      purescript ? null,
      remoteExecution ? null,
      extra ? "",
    }:
    let
      sections = lib.filter (s: s != null && s != "") [
        cxx
        haskell
        rust
        lean
        python
        nv
        purescript
        remoteExecution
        extra
      ];
    in
    ''
      # AUTO-GENERATED by nix develop
      # DO NOT EDIT - regenerated on each shell entry
      ${lib.concatStringsSep "\n" sections}
    '';

  # C++ toolchain section
  mkCxxSection =
    { llvmPackages }:
    let
      llvm = llvmPackages;
      inherit (pkgs) gcc;
      gcc-unwrapped = gcc.cc;
      gcc-version = gcc-unwrapped.version;
      triple = pkgs.stdenv.hostPlatform.config;
    in
    builtins.readFile (
      render-dhall "cxx-section" (scripts-dir + "/cxx-section.dhall") {
        cc = "${llvm.clang}/bin/clang";
        cxx = "${llvm.clang}/bin/clang++";
        cpp = "${llvm.clang}/bin/clang-cpp";
        ar = "${llvm.lld}/bin/llvm-ar";
        ld = "${llvm.lld}/bin/ld.lld";
        clang_resource_dir = "${llvm.clang}/resource-root";
        gcc_include = "${gcc-unwrapped}/include/c++/${gcc-version}";
        gcc_include_arch = "${gcc-unwrapped}/include/c++/${gcc-version}/${triple}";
        glibc_include = "${pkgs.glibc.dev}/include";
        gcc_lib = "${gcc-unwrapped}/lib/gcc/${triple}/${gcc-version}";
        gcc_lib_base = "${gcc.cc.lib}/lib";
        glibc_lib = "${pkgs.glibc}/lib";
      }
    );

  # Haskell toolchain section
  mkHaskellSection =
    {
      ghc,
      ghcVersion,
      ghcPkgWrapper ? null,
      stan ? null,
    }:
    builtins.readFile (
      render-dhall "haskell-section" (scripts-dir + "/haskell-section.dhall") {
        ghc = "${ghc}";
        ghc-version = "${ghcVersion}";
        ghc-pkg-wrapper = if ghcPkgWrapper != null then "${ghcPkgWrapper}" else "";
        stan = if stan != null then "${stan}" else "";
      }
    );

  # Rust toolchain section
  mkRustSection = _: ''

    [rust]
    rustc = ${pkgs.rustc}/bin/rustc
    rustdoc = ${pkgs.rustc}/bin/rustdoc
    clippy_driver = ${pkgs.clippy}/bin/clippy-driver
    cargo = ${pkgs.cargo}/bin/cargo
  '';

  # Lean toolchain section
  mkLeanSection =
    _:
    let
      lean = pkgs.lean4;
    in
    ''

      [lean]
      lean = ${lean}/bin/lean
      leanc = ${lean}/bin/leanc
      lean_lib_dir = ${lean}/lib/lean/library
      lean_include_dir = ${lean}/include
    '';

  # Python toolchain section
  mkPythonSection =
    {
      python,
      pybind11 ? null,
    }:
    let
      # Handle both plain python and python.withPackages results
      # withPackages returns an env that wraps the original python
      pythonPkg = python.passthru.pythonOnBuildForHost or python.passthru.python or python;
      pyVersion = lib.versions.majorMinor pythonPkg.version;
    in
    builtins.readFile (
      render-dhall "python-section" (scripts-dir + "/python-section.dhall") {
        python = "${python}";
        python-include = "${python}/include/python${pyVersion}";
        pybind11-include = if pybind11 != null then "${pybind11}/include" else "";
      }
    );

  # NVIDIA toolchain section
  mkNvSection =
    {
      nvidia-sdk,
      clang-unwrapped,
      mdspan,
    }:
    builtins.readFile (
      render-dhall "nv-section" (scripts-dir + "/nv-section.dhall") {
        nvidia-sdk = "${nvidia-sdk}";
        clang = "${clang-unwrapped}/bin/clang++";
        mdspan = "${mdspan}";
      }
    );

  # PureScript toolchain section
  mkPureScriptSection = _: ''

    [purescript]
    purs = ${pkgs.purescript}/bin/purs
    spago = ${pkgs.spago}/bin/spago
    node = ${pkgs.nodejs}/bin/node
  '';

  # Remote Execution section (NativeLink)
  mkRemoteExecutionSection =
    {
      scheduler,
      schedulerPort,
      cas,
      casPort,
      tls,
      instanceName,
    }:
    let
      tlsStr = if tls then "true" else "false";
    in
    builtins.readFile (
      render-dhall "remote-exec-section" (scripts-dir + "/remote-exec-section.dhall") {
        scheduler = "${scheduler}";
        scheduler-port = "${toString schedulerPort}";
        cas = "${cas}";
        cas-port = "${toString casPort}";
        tls = "${tlsStr}";
        instance-name = "${instanceName}";
      }
    );
}
