load("@toolchains//:haskell.bzl", "haskell_binary")

haskell_binary(
    name = "nix-analyze",
    srcs = ["Main.hs", "Nix.hs"],
    main = "Main",
    packages = ["base", "bytestring", "text", "process", "aeson", "containers"],
    language_extensions = ["LambdaCase", "OverloadedStrings"],
    ghc_options = ["-O2", "-Wall"],
    visibility = ["PUBLIC"],
)

