# src/examples/simdjson/BUCK
#
# simdjson demo - SIMD-accelerated JSON parsing at 4+ GB/s
#
# Demonstrates the Nix-Buck2 contract:
#   - deps = ["nixpkgs#simdjson"] - any derivation is valid
#   - nix_cxx_binary macro handles the resolution automatically

load("@toolchains//:nix_analyze.bzl", "nix_cxx_binary")

nix_cxx_binary(
    name = "twitter",
    srcs = ["twitter.cpp"],
    # Directly reference flake fragments in deps
    deps = ["nixpkgs#simdjson"],
    # Nix libraries (like simdjson) often use -std=c++17 or higher
    compiler_flags = ["-std=c++20", "-O2"],
    visibility = ["PUBLIC"],
)
